-- NDiplomacy

NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_DESIRE_AE_MODIFIER = 0
NDefines.NDiplomacy.AE_SAME_CULTURE = 0.25
NDefines.NDiplomacy.AE_SAME_RELIGION = 0.25
NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.3
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 10
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12

-- NCountry

NDefines.NCountry.PROSPERITY_INCREASE_SIZE= 2
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.BREAK_MARRIAGE_STABILITY_PENALTY = 0
NDefines.NCountry.RAZE_PROVINCE_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 0
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5

-- NEconomy

NDefines.NEconomy.CARAVAN_FACTOR = 6.0
NDefines.NEconomy.CARAVAN_POWER_MAX = 20

-- NMilitary

NDefines.NMilitary.GARRISON_SIZE = 2000
NDefines.NMilitary.FORTRESS_COST = 0.25
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.35

-- NAI

NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.8
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_FRIEND_IN_COMBAT = 0.7
NDefines.NAI.AGGRESSIVENESS = 1500
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 1000
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.95
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 15
NDefines.NAI.DESIRED_SURPLUS = 0.3
NDefines.NAI.DESIRED_DEFICIT = 0.2
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.25
NDefines.NAI.MAX_SAVINGS = 0.1
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.9
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.3
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 100
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 30
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 3
NDefines.NAI.FIRE_ADVISOR_LOAN_REQUIREMENT = 10
NDefines.NAI.DEVELOPMENT_CAP_BASE = 15
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 3
NDefines.NAI.DIPLOMATIC_ACTION_KNOWLEDGE_SHARING_ACCEPTANCE_MULT = 100.0
NDefines.NAI.INVADING_BRAVERY = 2.0
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1.45
NDefines.NAI.HOME_FLEET_MAX_RATIO = 0.6
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 5.0
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.01
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.4
NDefines.NAI.ESTATE_PRIVILEGE_REVOKE_THRESHOLD = 7
NDefines.NAI.ESTATE_INTERACTION_THRESHOLD = 25.0
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 89.9
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 0.0
NDefines.NAI.ESTATE_PRIVILEGE_GRANT_THRESHOLD = 0
NDefines.NAI.ESTATE_MAX_PRIVILEGES = 6
NDefines.NAI.BUDGETING_ADJUSTMENT_STEP = 0.02

